### ISSUE TITLE
Incorrect display of date as 0NaN.aN.aN aN:aN pm

### ISSUE THREAD

**Issue by kfinley** [vuejs-community/vue-filter-date-format#162]
I've seen this sporadicly in Chromium but pretty consistently in Safari both on MacOS and iOS.

<p>Published on: {{new Date(a.pub_date) | dateFormat('YYYY.MM.DD hh:mm a')}}</p>

will display:

Published on: 0NaN.aN.aN aN:aN pm

The value for pub_date in this example is:

pub_date: "2020-04-28T09:00:30+0000"

MacOS: Version 10.15.3
Safari: Version 13.0.5 (15608.5.11)

iOS: Version 13.3

**Comment by eduardnikolenko** [comment]
Hi, @kfinley 
`2020-04-28T09:00:30+0000` is not valid json date format.
In You case dateFormat filter called with Date object marked at InvalidDate.

**Comment by kfinley** [comment]
I noticed that after the fact. Chromium handled the date fine while Safari didn't. The date format was returned from a NYT API so they send an invalid json date format. Bummer but whatever.
