### ISSUE TITLE
Allow to select UTC timestamp

### ISSUE THREAD

**Issue by BenBE** [vuejs-community/vue-filter-date-format#193]
Allow to specify the UTC timestamp should be formatted instead of the local time.

Mostly this requires changing `input.getX()` to `input.getUTCX()` based on some additional argument.

**Comment by eduardnikolenko** [comment]
Hi.
Now You can use `timezone` option to specify timezone instead of the local time.

**Comment by BenBE** [comment]
Doing `{{someDateTimeValue | dateFormat('YYYY-MM-DD HH:mm:ss.SSS', {timezone: 0})}}` still gives local time.
As far as I understand the code, this is due to the fact, that the check in `dateFormat` checks for anything that's a truethy value, which 0 is not. When I configure `{timezone: 0.000000000001}` I get the expected output.
