### ISSUE TITLE
I Get Error in vue typescript input.getFullYear is not a function

### ISSUE THREAD

**Issue by rishidevkota** [vuejs-community/vue-filter-date-format#212]
TypeError: input.getFullYear is not a function
    at dateFormat (vue-filter-date-format.esm.js?11c8:54)
    at eval (vue-filter-date-format.esm.js?11c8:113)

**Comment by eduardnikolenko** [comment]
Hi.
Maybe You input not a Date object?

**Comment by jonezineworks** [comment]
use it like this
 {{ new Date( *your date* ) | dateFormat('DD.MM.YYYY hh:mm') }}

**Comment by eduardnikolenko** [comment]
Duplicate #129
