### ISSUE TITLE
Millisecond support?

### ISSUE THREAD

**Issue by jonezineworks** [vuejs-community/vue-filter-date-format#224]
Is there any plan to add millisecond precision?

**Comment by eduardnikolenko** [comment]
Hi, @jonezineworks.
I started work on this.

**Comment by eduardnikolenko** [comment]
Hi, @jonezineworks.
Now You can use `S` or `SSS` token for output milliseconds, this feature available from version 1.6.1.

| Key    | Output                                 |
| ------ | -------------------------------------- |
| `S`    | 0 1 ... 58 59                          |
| `SSS`  | 000 001 ... 058 059                    |

**Comment by jonezineworks** [comment]
Awesome! Thank you.
