### ISSUE TITLE
Failed to resolve filter: dateFormat in Nuxt

### ISSUE THREAD

**Issue by faizalami** [vuejs-community/vue-filter-date-format#245]
Nuxt version: 2.14.4

I got warn _[Vue warn]: Failed to resolve filter: dateFormat_ in Nuxt, but the filter is working. I think the problem is because I use client mode to import this filter in **nuxt.config.js**. I think like that because I also made another global filter and import it in ssr mode (without mode: 'client' option) and it is working perfectly. Unfortunately, this plugin is not working in ssr mode, so I imported this plugin in client mode.
```js
plugins: [
  { src: '~/filters/filter-date-format', mode: 'client' },
]
```
in the vue component:
```js
{{ new Date() | dateFormat('YYYY MMM DD') }}
```

the result:
![image](https://user-images.githubusercontent.com/6519497/93168625-8ab6ce00-f74d-11ea-8acd-04fdd95326b5.png)
it's working, but
![image](https://user-images.githubusercontent.com/6519497/93169255-eafa3f80-f74e-11ea-8ec4-53e4e1235274.png)

I have tried to add <client-only> component but it still reproduce that warn. So, is there a solution to solve this?

**Comment by eduardnikolenko** [comment]
Hi.
Thank you for the detailed description of the problem.
This plugin is working in SSR mode, but version 1.6.1 have bug in CommonJS build, please update to 1.6.2
Working example with Nuxt [here](https://codesandbox.io/s/inspiring-austin-eibtc)

**Comment by faizalami** [comment]
okay thanks, i will try it

actually i found a funny solution, i wrote a new plugin declaration bellow to declare a dummy filter to register it in ssr mode, and then this actual dateFormat filter will overload it in client mode

```js
// filters/filter-date-format-init.js
import Vue from 'vue';

Vue.filter('dateFormat', content => content);
```

in nuxt.config.js
```js
{

  plugins: [
    '~/filters/filter-date-format-init',
    { src: '~/filters/filter-date-format', mode: 'client' },
  ],
}
```
