### ISSUE TITLE
Module default format should be ISO-8601

### ISSUE THREAD

**Issue by BenBE** [vuejs-community/vue-filter-date-format#262]
Currently the default date format is some exotic variant (`YYYY.MM.DD …`) that's used in about two countries in the world. Would appreciate, if the module could switch to ISO-8601 (`YYYY-MM-DD …`) for the default format, which is much more commonly used.

Apart from that: In the list of weekdays, it should be `Th` instead of `Tr` for `Thursday`.

**Comment by eduardnikolenko** [comment]
Fixed in version 1.6.3
